version: '2'

services:
  vis:
    image: wolverine2k/docker_vidac-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './vidac:/var/vidac'
    ports:
      - '3000:3000'
      - '3001:3001'
    depends_on:
      - mongodb
      - rabbitmq
    links:
      - mongodb
      - rabbitmq
      - elasticsearch
      - kibana

  mongodb:
    image: mongo:3.3.10
    volumes:
      - './mongodb:/data/db'

  rabbitmq:
    image: rabbitmq:3.6.5
    volumes:
      - './rabbitmq:/var/lib/rabbitmq'

  elasticsearch:
    image: elasticsearch:5.0.0-alpha5
    volumes:
      - './elasticsearch:/usr/share/elasticsearch/data'
    environment:
      - ES_JAVA_OPTS="-Xms1g -Xmx1g"
      - bootstrap.ignore_system_bootstrap_checks=true
      - bootstrap.seccomp=false
      - http.cors.enabled=true
      - http.cors.allow.origin=1

  kibana:
    image: kibana:5.0.0-alpha4