version: '2'

services:
  node:
    build:
      context: .
      dockerfile: node.vidac.dockerfile
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "3000:3000"
      - "3001:3001"
    links:
      - mongodb
      - rabbitmq
      - elasticsearch
      - kibana

  mongodb:
    image: mongo:3.3.10

  rabbitmq:
    image: rabbitmq:3.6.5

  elasticsearch:
    image: elasticsearch:5.0.0-alpha5

  kibana:
    image: kibana:5.0.0-alpha4